Search contacts
vmix-woolf/colibri-team-project pull request #38
Opened 2024-11-07 19:07 UTC by Anastasia-Danyliuk

2024-11-07 19:53 UTC, Kolisya20 requested changes

2024-11-07 19:53 UTC, Kolisya20 commented on handlers/handler.py
> +    if len(args) < 1:
It should be before parsing the arguments

2024-11-07 19:53 UTC, Kolisya20 commented on handlers/handler.py
> +
А що буде якщо такого контакту не знайдено?

2024-11-07 19:53 UTC, Kolisya20 commented on handlers/handler.py
> +    return addressbook.find_by_birthday(birthday)
Те саме питання - якщо немає даних - має бути повернуто щось інше - якесь повідомлення

2024-11-07 19:53 UTC, Kolisya20 commented on handlers/handler.py
> +    return addressbook.find_by_email(email)
Ну і туь

2024-11-07 19:53 UTC, Kolisya20 commented on main.py
> +            print(show_contacts(search_by_name(args, addressbook), Constants.NO_CONTACTS_WITH_NAME.value))
я бачу що ти хотіла перевикористати метод show contacts, але на мою думку - show і search це зовсім різні штуки і краще їх розділити - і до кожної окремої функції використовувати format table.

2024-11-07 20:03 UTC, Anastasia-Danyliuk commented on main.py
> +            print(show_contacts(search_by_name(args, addressbook), Constants.NO_CONTACTS_WITH_NAME.value))
Так це і є різні методи, метод серч повертає рекорд або список рекордів (залежить від аргумнта)
А метод шоу контактс відповідає за вивід контактів, яких ми найшли через серч. 
Навіщо робити для кожної функції формат тейбл якщо можна перевикористати метод шоу контактс?
шоу контактс відповідає за вивід, серч за пошук - я їх якраз не обєдную

2024-11-07 20:05 UTC, Anastasia-Danyliuk commented on handlers/handler.py
> +
Повертає None
Ми цей None перевіряємо у методі show_contacts, переглянь його і атрибут errorMessage

2024-11-07 20:05 UTC, Anastasia-Danyliuk commented on handlers/handler.py
> +    return addressbook.find_by_birthday(birthday)
Повертає пустий список
Ми цей пустий список перевіряємо у методі show_contacts, переглянь його і атрибут errorMessage

2024-11-07 20:05 UTC, Anastasia-Danyliuk commented on handlers/handler.py
> +    return addressbook.find_by_email(email)
Повертає None
Ми цей None перевіряємо у методі show_contacts, переглянь його і атрибут errorMessage

2024-11-07 20:11 UTC, Anastasia-Danyliuk commented on main.py
> +            print(show_contacts(search_by_name(args, addressbook), Constants.NO_CONTACTS_WITH_NAME.value))
Чи ти маєш на увазі перейменувати show_contacts на format_contacts?

2024-11-07 20:27 UTC, Anastasia-Danyliuk commented on handlers/handler.py
> +    if len(args) < 1:
Виправила. Дякую)

2024-11-08 06:04 UTC, vmix-woolf commented on handlers/handler.py
> +    return addressbook.find_by_birthday(birthday)
Информацию о show-email нужно добаить в readme в соответствующий раздел

2024-11-08 06:10 UTC, vmix-woolf commented on assistant/addressbook.py
> +        return None
Если мы не нашли никакую запись, то это значит что record=None поэтому find_email_email вернёт None, так как функции по умолчанию возвращают None если не передать return, то последнее return None можно не указывать. Проверь без return None, должно работать. Код будет более лёгок для понимания

2024-11-08 06:17 UTC, vmix-woolf commented on handlers/handler.py
>          return format_table(fields, records_list)
if not contacts:
    return error_message

# Ensure `contacts` is a list of `Record` objects
records_list = [contacts] if isinstance(contacts, Record) else list(contacts)

if not records_list:
    return error_message

fields = ["Name", "Phones", "Address", "Email", "Birthday"]
return format_table(fields, records_list)

попробуй так, должно работать, у тебя сильно много if-ов

2024-11-08 06:20 UTC, vmix-woolf commented on handlers/handler.py
>          return format_table(fields, records_list)
там после # надо убрать // тут странное форматирование, я их оставил чтобы не показывался коммент заголовком. Похоже что здесь md -форматирование по умолчанию

2024-11-08 09:20 UTC, Anastasia-Danyliuk commented on handlers/handler.py
>          return format_table(fields, records_list)
Тоді код неправильно працюватиме, залишаю як є
![image](https://github.com/user-attachments/assets/48c2952d-c888-4360-b08d-c9c001077196)

2024-11-08 09:22 UTC, Kolisya20 commented on main.py
> +            print(show_contacts(search_by_name(args, addressbook), Constants.NO_CONTACTS_WITH_NAME.value))
аргументи прийнято) давай дійно перйменуємо - щоб було зрозуміло що функція саме форматує дані - і перевіримо що все працює

2024-11-08 09:28 UTC, Anastasia-Danyliuk commented on main.py
> +            print(show_contacts(search_by_name(args, addressbook), Constants.NO_CONTACTS_WITH_NAME.value))
Перейменувала

2024-11-08 09:28 UTC, Anastasia-Danyliuk commented on assistant/addressbook.py
> +        return None
Видалила, дякую

2024-11-08 20:29 UTC, merged